# References {.unnumbered}

::: {#refs}
:::
Aasen, H.et al. (2018) ‘Quantitative Remote Sensing at Ultra High Resolution with UAV
Spectroscopy: A Review of Sensor Technology, Measurement Procedures, and Data
Correction Workflows’, Remote Sensing , 10(7), p. 1091. Available at:
https://doi.org/10.3390/rs10071091.

Amani, M. et al. (2020) ‘Google Earth Engine Cloud Computing Platform for Remote Sensing
Big Data Applications: A Comprehensive Review’, IEEE Journal of Selected Topics in Applied
Earth Observations and Remote Sensing , 13, pp. 5326 5350. Available at:
https:https://doi.org/10.1109/JSTARS.

Blaschke, T. (2010) ‘Object based image analysis for remote sensing’,ISPRS Journal of
Photogrammetry and Remote Sensing , 65(1), pp. 2 16. Available at:
https://doi.org/10.1016/j.isprsjprs.2009.06.004.

Brady M. (2021) Remote Sensing for Dummies , ArcGIS StoryMaps . Available at:
https://storymaps.arcgis.com/stories/cb1577b0f5bc485c974b4ea19d52282d (Accessed: 30 January 2023).

Brivio, P.A.et al. (2002) ‘Integration of remote sensing data and GIS for accurate mapping of
f looded areas’, International Journal of Remote Sensing , 23(3), pp. 429 441. Available at:
https://doi.org/10.1080/01431160010014729.

Butcher, G. (2016)Tour of the electromagnetic spectrum . Third edition. Washington, DC:
National Aeronautics and Space Admi nistration.

Chen, G.et al. (2018) ‘Geographic object based image analysis (GEOBIA): emerging trends
and future opportunities’, GIScience & Remote Sensing , 55(2), pp. 159 182. Available at:
https://doi.org/10.1080/15481603.2018.1426092.

Chen, J.et al. (20 09) ‘Generalization of Subpixel Analysis for Hyperspectral Data With Flexibility in Spectral Similarity Measures’, IEEE Transactions on Geoscience and Remote Sensing , 47(7),pp. 2165 2171. Available at: https://doi.org/10.1109/TGRS.2008.2011432.

Hilker, T.et al. (2012) ‘Remote sensing of tropical ecosystems: Atmospheric correction and
cloud masking matter’, Remote Sensing of Environment , 127, pp. 370 384. Available at:
https://doi.org/10.1016/j.rse.2012.08.035.

Impacts of Climate Change on Public Health in
India: Future Research Directions (no date).
Available at:https://doi.org/10.1289/ehp.1003000.

Knowlton, K.et al. (2014) ‘Development and Implementation of South Asia’s First Heat Health
Action Plan in Ahmedabad (Gujarat, India)’, International Journal of Environmental Research
and Public Health , 11(4), pp. 3473 3492. Available at:
https://doi.org/10.3390/ijerph110403473.

Pal, M. and Mather, P.M. (2005) ‘Support vector machines for classification in remote sensing’,
Pal, M. and Mather, P.M. (2005) ‘Support vector machines for classification in remote sensing’, International Journal of Remote SensinInternational Journal of Remote Sensingg, 26(5), pp. 1007, 26(5), pp. 1007––1011. Available at: 1011. Available at: https://doi.org/10.1080/01431160512331314083.https://doi.org/10.1080/01431160512331314083.

Toutin, T. (2011) ‘State Toutin, T. (2011) ‘State--ofof--thethe--art of geometric correction of remote sensing data: a data art of geometric correction of remote sensing data: a data fusion perspective’, fusion perspective’, International Journal of Image and Data FusionInternational Journal of Image and Data Fusion, 2(1), pp. 3, 2(1), pp. 3––35. Available 35. Available at: https://doi.org/10.1080/19479832.2010.539188.at: https://doi.org/10.1080/19479832.2010.539188.


‘Unmanned aerial vehicles for environmental applications’ (2017) International Journal of International Journal of Remote SensingRemote Sensing, 38(8, 38(8––10), pp. 202910), pp. 2029––2036. Available at: 2036. Available at: https://doi.org/10.1080/01431161.2017.1301705.https://doi.org/10.1080/01431161.2017.1301705.

Xu, M. et al (2005) ‘Decision tree regression for soft classification of remote sensing data’, (2005) ‘Decision tree regression for soft classification of remote sensing data’, Remote Sensing of EnvironmentRemote Sensing of Environment, 97(3), pp. 322, 97(3), pp. 322––336. Available at: 336. Available at: https://doi.org/10.1016/j.rse.2005.05.008.https://doi.org/10.1016/j.rse.2005.05.008.


Yang, J. et al. (2019) ‘Migration of barchan dunes (2019) ‘Migration of barchan dunes in the western Quruq Desert, northwestern in the western Quruq Desert, northwestern China’, China’, Earth Surface Processes and LandformsEarth Surface Processes and Landforms, 44(10), pp. 2016, 44(10), pp. 2016––2029. Available at: 2029. Available at: https://doi.org/10.1002/esp.4629.https://doi.org/10.1002/esp.4629.


Georgeeorge et al.(2022) 'Urban heat island patch identification and spatial expansion path: A case 'Urban heat island patch identification and spatial expansion path: A case study of Beijing'study of Beijing',, Scientia Geographica SinicaScientia Geographica Sinica 42(8), pp. 149242(8), pp. 1492––1501. Available at: 1501. Available at: https://doi.org/10.13249/j.cnki.sgs.2022.08.017.

Jun, Xun, et al.(2023) ‘Impermeable surface extraction based on GEE and machine learning: A Impermeable surface extraction based on GEE and machine learning: A case study of Chengducase study of Chengdu--Chongqiing Area'Chongqiing Area',, Engineering of Surveying and Mapping,Engineering of Surveying and Mapping, 32(2), pp. 32(2), pp. 2121––29. Available at: https://doi.org/10.19349/j.cnki.issn100629. 